package twitter4j.internal.json;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import twitter4j.HashtagEntity;
import twitter4j.MediaEntity;
import twitter4j.URLEntity;
import twitter4j.UserMentionEntity;

final class HTMLEntity
{
  private static final Map<java.lang.String, java.lang.String> entityEscapeMap = new HashMap();
  private static final Map<java.lang.String, java.lang.String> escapeEntityMap = new HashMap();
  
  static
  {
    java.lang.String[][] arrayOfString; = new java.lang.String['û'][];
    java.lang.String[] arrayOfString1 = new java.lang.String[3];
    arrayOfString1[0] = "&nbsp;";
    arrayOfString1[1] = "&#160;";
    arrayOfString1[2] = " ";
    arrayOfString;[0] = arrayOfString1;
    java.lang.String[] arrayOfString2 = new java.lang.String[3];
    arrayOfString2[0] = "&iexcl;";
    arrayOfString2[1] = "&#161;";
    arrayOfString2[2] = "¡";
    arrayOfString;[1] = arrayOfString2;
    java.lang.String[] arrayOfString3 = new java.lang.String[3];
    arrayOfString3[0] = "&cent;";
    arrayOfString3[1] = "&#162;";
    arrayOfString3[2] = "¢";
    arrayOfString;[2] = arrayOfString3;
    java.lang.String[] arrayOfString4 = new java.lang.String[3];
    arrayOfString4[0] = "&pound;";
    arrayOfString4[1] = "&#163;";
    arrayOfString4[2] = "£";
    arrayOfString;[3] = arrayOfString4;
    java.lang.String[] arrayOfString5 = new java.lang.String[3];
    arrayOfString5[0] = "&curren;";
    arrayOfString5[1] = "&#164;";
    arrayOfString5[2] = "¤";
    arrayOfString;[4] = arrayOfString5;
    java.lang.String[] arrayOfString6 = new java.lang.String[3];
    arrayOfString6[0] = "&yen;";
    arrayOfString6[1] = "&#165;";
    arrayOfString6[2] = "¥";
    arrayOfString;[5] = arrayOfString6;
    java.lang.String[] arrayOfString7 = new java.lang.String[3];
    arrayOfString7[0] = "&brvbar;";
    arrayOfString7[1] = "&#166;";
    arrayOfString7[2] = "¦";
    arrayOfString;[6] = arrayOfString7;
    java.lang.String[] arrayOfString8 = new java.lang.String[3];
    arrayOfString8[0] = "&sect;";
    arrayOfString8[1] = "&#167;";
    arrayOfString8[2] = "§";
    arrayOfString;[7] = arrayOfString8;
    java.lang.String[] arrayOfString9 = new java.lang.String[3];
    arrayOfString9[0] = "&uml;";
    arrayOfString9[1] = "&#168;";
    arrayOfString9[2] = "¨";
    arrayOfString;[8] = arrayOfString9;
    java.lang.String[] arrayOfString10 = new java.lang.String[3];
    arrayOfString10[0] = "&copy;";
    arrayOfString10[1] = "&#169;";
    arrayOfString10[2] = "©";
    arrayOfString;[9] = arrayOfString10;
    java.lang.String[] arrayOfString11 = new java.lang.String[3];
    arrayOfString11[0] = "&ordf;";
    arrayOfString11[1] = "&#170;";
    arrayOfString11[2] = "ª";
    arrayOfString;[10] = arrayOfString11;
    java.lang.String[] arrayOfString12 = new java.lang.String[3];
    arrayOfString12[0] = "&laquo;";
    arrayOfString12[1] = "&#171;";
    arrayOfString12[2] = "«";
    arrayOfString;[11] = arrayOfString12;
    java.lang.String[] arrayOfString13 = new java.lang.String[3];
    arrayOfString13[0] = "&not;";
    arrayOfString13[1] = "&#172;";
    arrayOfString13[2] = "¬";
    arrayOfString;[12] = arrayOfString13;
    java.lang.String[] arrayOfString14 = new java.lang.String[3];
    arrayOfString14[0] = "&shy;";
    arrayOfString14[1] = "&#173;";
    arrayOfString14[2] = "­";
    arrayOfString;[13] = arrayOfString14;
    java.lang.String[] arrayOfString15 = new java.lang.String[3];
    arrayOfString15[0] = "&reg;";
    arrayOfString15[1] = "&#174;";
    arrayOfString15[2] = "®";
    arrayOfString;[14] = arrayOfString15;
    java.lang.String[] arrayOfString16 = new java.lang.String[3];
    arrayOfString16[0] = "&macr;";
    arrayOfString16[1] = "&#175;";
    arrayOfString16[2] = "¯";
    arrayOfString;[15] = arrayOfString16;
    java.lang.String[] arrayOfString17 = new java.lang.String[3];
    arrayOfString17[0] = "&deg;";
    arrayOfString17[1] = "&#176;";
    arrayOfString17[2] = "°";
    arrayOfString;[16] = arrayOfString17;
    java.lang.String[] arrayOfString18 = new java.lang.String[3];
    arrayOfString18[0] = "&plusmn;";
    arrayOfString18[1] = "&#177;";
    arrayOfString18[2] = "±";
    arrayOfString;[17] = arrayOfString18;
    java.lang.String[] arrayOfString19 = new java.lang.String[3];
    arrayOfString19[0] = "&sup2;";
    arrayOfString19[1] = "&#178;";
    arrayOfString19[2] = "²";
    arrayOfString;[18] = arrayOfString19;
    java.lang.String[] arrayOfString20 = new java.lang.String[3];
    arrayOfString20[0] = "&sup3;";
    arrayOfString20[1] = "&#179;";
    arrayOfString20[2] = "³";
    arrayOfString;[19] = arrayOfString20;
    java.lang.String[] arrayOfString21 = new java.lang.String[3];
    arrayOfString21[0] = "&acute;";
    arrayOfString21[1] = "&#180;";
    arrayOfString21[2] = "´";
    arrayOfString;[20] = arrayOfString21;
    java.lang.String[] arrayOfString22 = new java.lang.String[3];
    arrayOfString22[0] = "&micro;";
    arrayOfString22[1] = "&#181;";
    arrayOfString22[2] = "µ";
    arrayOfString;[21] = arrayOfString22;
    java.lang.String[] arrayOfString23 = new java.lang.String[3];
    arrayOfString23[0] = "&para;";
    arrayOfString23[1] = "&#182;";
    arrayOfString23[2] = "¶";
    arrayOfString;[22] = arrayOfString23;
    java.lang.String[] arrayOfString24 = new java.lang.String[3];
    arrayOfString24[0] = "&middot;";
    arrayOfString24[1] = "&#183;";
    arrayOfString24[2] = "·";
    arrayOfString;[23] = arrayOfString24;
    java.lang.String[] arrayOfString25 = new java.lang.String[3];
    arrayOfString25[0] = "&cedil;";
    arrayOfString25[1] = "&#184;";
    arrayOfString25[2] = "¸";
    arrayOfString;[24] = arrayOfString25;
    java.lang.String[] arrayOfString26 = new java.lang.String[3];
    arrayOfString26[0] = "&sup1;";
    arrayOfString26[1] = "&#185;";
    arrayOfString26[2] = "¹";
    arrayOfString;[25] = arrayOfString26;
    java.lang.String[] arrayOfString27 = new java.lang.String[3];
    arrayOfString27[0] = "&ordm;";
    arrayOfString27[1] = "&#186;";
    arrayOfString27[2] = "º";
    arrayOfString;[26] = arrayOfString27;
    java.lang.String[] arrayOfString28 = new java.lang.String[3];
    arrayOfString28[0] = "&raquo;";
    arrayOfString28[1] = "&#187;";
    arrayOfString28[2] = "»";
    arrayOfString;[27] = arrayOfString28;
    java.lang.String[] arrayOfString29 = new java.lang.String[3];
    arrayOfString29[0] = "&frac14;";
    arrayOfString29[1] = "&#188;";
    arrayOfString29[2] = "¼";
    arrayOfString;[28] = arrayOfString29;
    java.lang.String[] arrayOfString30 = new java.lang.String[3];
    arrayOfString30[0] = "&frac12;";
    arrayOfString30[1] = "&#189;";
    arrayOfString30[2] = "½";
    arrayOfString;[29] = arrayOfString30;
    java.lang.String[] arrayOfString31 = new java.lang.String[3];
    arrayOfString31[0] = "&frac34;";
    arrayOfString31[1] = "&#190;";
    arrayOfString31[2] = "¾";
    arrayOfString;[30] = arrayOfString31;
    java.lang.String[] arrayOfString32 = new java.lang.String[3];
    arrayOfString32[0] = "&iquest;";
    arrayOfString32[1] = "&#191;";
    arrayOfString32[2] = "¿";
    arrayOfString;[31] = arrayOfString32;
    java.lang.String[] arrayOfString33 = new java.lang.String[3];
    arrayOfString33[0] = "&Agrave;";
    arrayOfString33[1] = "&#192;";
    arrayOfString33[2] = "À";
    arrayOfString;[32] = arrayOfString33;
    java.lang.String[] arrayOfString34 = new java.lang.String[3];
    arrayOfString34[0] = "&Aacute;";
    arrayOfString34[1] = "&#193;";
    arrayOfString34[2] = "Á";
    arrayOfString;[33] = arrayOfString34;
    java.lang.String[] arrayOfString35 = new java.lang.String[3];
    arrayOfString35[0] = "&Acirc;";
    arrayOfString35[1] = "&#194;";
    arrayOfString35[2] = "Â";
    arrayOfString;[34] = arrayOfString35;
    java.lang.String[] arrayOfString36 = new java.lang.String[3];
    arrayOfString36[0] = "&Atilde;";
    arrayOfString36[1] = "&#195;";
    arrayOfString36[2] = "Ã";
    arrayOfString;[35] = arrayOfString36;
    java.lang.String[] arrayOfString37 = new java.lang.String[3];
    arrayOfString37[0] = "&Auml;";
    arrayOfString37[1] = "&#196;";
    arrayOfString37[2] = "Ä";
    arrayOfString;[36] = arrayOfString37;
    java.lang.String[] arrayOfString38 = new java.lang.String[3];
    arrayOfString38[0] = "&Aring;";
    arrayOfString38[1] = "&#197;";
    arrayOfString38[2] = "Å";
    arrayOfString;[37] = arrayOfString38;
    java.lang.String[] arrayOfString39 = new java.lang.String[3];
    arrayOfString39[0] = "&AElig;";
    arrayOfString39[1] = "&#198;";
    arrayOfString39[2] = "Æ";
    arrayOfString;[38] = arrayOfString39;
    java.lang.String[] arrayOfString40 = new java.lang.String[3];
    arrayOfString40[0] = "&Ccedil;";
    arrayOfString40[1] = "&#199;";
    arrayOfString40[2] = "Ç";
    arrayOfString;[39] = arrayOfString40;
    java.lang.String[] arrayOfString41 = new java.lang.String[3];
    arrayOfString41[0] = "&Egrave;";
    arrayOfString41[1] = "&#200;";
    arrayOfString41[2] = "È";
    arrayOfString;[40] = arrayOfString41;
    java.lang.String[] arrayOfString42 = new java.lang.String[3];
    arrayOfString42[0] = "&Eacute;";
    arrayOfString42[1] = "&#201;";
    arrayOfString42[2] = "É";
    arrayOfString;[41] = arrayOfString42;
    java.lang.String[] arrayOfString43 = new java.lang.String[3];
    arrayOfString43[0] = "&Ecirc;";
    arrayOfString43[1] = "&#202;";
    arrayOfString43[2] = "Ê";
    arrayOfString;[42] = arrayOfString43;
    java.lang.String[] arrayOfString44 = new java.lang.String[3];
    arrayOfString44[0] = "&Euml;";
    arrayOfString44[1] = "&#203;";
    arrayOfString44[2] = "Ë";
    arrayOfString;[43] = arrayOfString44;
    java.lang.String[] arrayOfString45 = new java.lang.String[3];
    arrayOfString45[0] = "&Igrave;";
    arrayOfString45[1] = "&#204;";
    arrayOfString45[2] = "Ì";
    arrayOfString;[44] = arrayOfString45;
    java.lang.String[] arrayOfString46 = new java.lang.String[3];
    arrayOfString46[0] = "&Iacute;";
    arrayOfString46[1] = "&#205;";
    arrayOfString46[2] = "Í";
    arrayOfString;[45] = arrayOfString46;
    java.lang.String[] arrayOfString47 = new java.lang.String[3];
    arrayOfString47[0] = "&Icirc;";
    arrayOfString47[1] = "&#206;";
    arrayOfString47[2] = "Î";
    arrayOfString;[46] = arrayOfString47;
    java.lang.String[] arrayOfString48 = new java.lang.String[3];
    arrayOfString48[0] = "&Iuml;";
    arrayOfString48[1] = "&#207;";
    arrayOfString48[2] = "Ï";
    arrayOfString;[47] = arrayOfString48;
    java.lang.String[] arrayOfString49 = new java.lang.String[3];
    arrayOfString49[0] = "&ETH;";
    arrayOfString49[1] = "&#208;";
    arrayOfString49[2] = "Ð";
    arrayOfString;[48] = arrayOfString49;
    java.lang.String[] arrayOfString50 = new java.lang.String[3];
    arrayOfString50[0] = "&Ntilde;";
    arrayOfString50[1] = "&#209;";
    arrayOfString50[2] = "Ñ";
    arrayOfString;[49] = arrayOfString50;
    java.lang.String[] arrayOfString51 = new java.lang.String[3];
    arrayOfString51[0] = "&Ograve;";
    arrayOfString51[1] = "&#210;";
    arrayOfString51[2] = "Ò";
    arrayOfString;[50] = arrayOfString51;
    java.lang.String[] arrayOfString52 = new java.lang.String[3];
    arrayOfString52[0] = "&Oacute;";
    arrayOfString52[1] = "&#211;";
    arrayOfString52[2] = "Ó";
    arrayOfString;[51] = arrayOfString52;
    java.lang.String[] arrayOfString53 = new java.lang.String[3];
    arrayOfString53[0] = "&Ocirc;";
    arrayOfString53[1] = "&#212;";
    arrayOfString53[2] = "Ô";
    arrayOfString;[52] = arrayOfString53;
    java.lang.String[] arrayOfString54 = new java.lang.String[3];
    arrayOfString54[0] = "&Otilde;";
    arrayOfString54[1] = "&#213;";
    arrayOfString54[2] = "Õ";
    arrayOfString;[53] = arrayOfString54;
    java.lang.String[] arrayOfString55 = new java.lang.String[3];
    arrayOfString55[0] = "&Ouml;";
    arrayOfString55[1] = "&#214;";
    arrayOfString55[2] = "Ö";
    arrayOfString;[54] = arrayOfString55;
    java.lang.String[] arrayOfString56 = new java.lang.String[3];
    arrayOfString56[0] = "&times;";
    arrayOfString56[1] = "&#215;";
    arrayOfString56[2] = "×";
    arrayOfString;[55] = arrayOfString56;
    java.lang.String[] arrayOfString57 = new java.lang.String[3];
    arrayOfString57[0] = "&Oslash;";
    arrayOfString57[1] = "&#216;";
    arrayOfString57[2] = "Ø";
    arrayOfString;[56] = arrayOfString57;
    java.lang.String[] arrayOfString58 = new java.lang.String[3];
    arrayOfString58[0] = "&Ugrave;";
    arrayOfString58[1] = "&#217;";
    arrayOfString58[2] = "Ù";
    arrayOfString;[57] = arrayOfString58;
    java.lang.String[] arrayOfString59 = new java.lang.String[3];
    arrayOfString59[0] = "&Uacute;";
    arrayOfString59[1] = "&#218;";
    arrayOfString59[2] = "Ú";
    arrayOfString;[58] = arrayOfString59;
    java.lang.String[] arrayOfString60 = new java.lang.String[3];
    arrayOfString60[0] = "&Ucirc;";
    arrayOfString60[1] = "&#219;";
    arrayOfString60[2] = "Û";
    arrayOfString;[59] = arrayOfString60;
    java.lang.String[] arrayOfString61 = new java.lang.String[3];
    arrayOfString61[0] = "&Uuml;";
    arrayOfString61[1] = "&#220;";
    arrayOfString61[2] = "Ü";
    arrayOfString;[60] = arrayOfString61;
    java.lang.String[] arrayOfString62 = new java.lang.String[3];
    arrayOfString62[0] = "&Yacute;";
    arrayOfString62[1] = "&#221;";
    arrayOfString62[2] = "Ý";
    arrayOfString;[61] = arrayOfString62;
    java.lang.String[] arrayOfString63 = new java.lang.String[3];
    arrayOfString63[0] = "&THORN;";
    arrayOfString63[1] = "&#222;";
    arrayOfString63[2] = "Þ";
    arrayOfString;[62] = arrayOfString63;
    java.lang.String[] arrayOfString64 = new java.lang.String[3];
    arrayOfString64[0] = "&szlig;";
    arrayOfString64[1] = "&#223;";
    arrayOfString64[2] = "ß";
    arrayOfString;[63] = arrayOfString64;
    java.lang.String[] arrayOfString65 = new java.lang.String[3];
    arrayOfString65[0] = "&agrave;";
    arrayOfString65[1] = "&#224;";
    arrayOfString65[2] = "à";
    arrayOfString;[64] = arrayOfString65;
    java.lang.String[] arrayOfString66 = new java.lang.String[3];
    arrayOfString66[0] = "&aacute;";
    arrayOfString66[1] = "&#225;";
    arrayOfString66[2] = "á";
    arrayOfString;[65] = arrayOfString66;
    java.lang.String[] arrayOfString67 = new java.lang.String[3];
    arrayOfString67[0] = "&acirc;";
    arrayOfString67[1] = "&#226;";
    arrayOfString67[2] = "â";
    arrayOfString;[66] = arrayOfString67;
    java.lang.String[] arrayOfString68 = new java.lang.String[3];
    arrayOfString68[0] = "&atilde;";
    arrayOfString68[1] = "&#227;";
    arrayOfString68[2] = "ã";
    arrayOfString;[67] = arrayOfString68;
    java.lang.String[] arrayOfString69 = new java.lang.String[3];
    arrayOfString69[0] = "&auml;";
    arrayOfString69[1] = "&#228;";
    arrayOfString69[2] = "ä";
    arrayOfString;[68] = arrayOfString69;
    java.lang.String[] arrayOfString70 = new java.lang.String[3];
    arrayOfString70[0] = "&aring;";
    arrayOfString70[1] = "&#229;";
    arrayOfString70[2] = "å";
    arrayOfString;[69] = arrayOfString70;
    java.lang.String[] arrayOfString71 = new java.lang.String[3];
    arrayOfString71[0] = "&aelig;";
    arrayOfString71[1] = "&#230;";
    arrayOfString71[2] = "æ";
    arrayOfString;[70] = arrayOfString71;
    java.lang.String[] arrayOfString72 = new java.lang.String[3];
    arrayOfString72[0] = "&ccedil;";
    arrayOfString72[1] = "&#231;";
    arrayOfString72[2] = "ç";
    arrayOfString;[71] = arrayOfString72;
    java.lang.String[] arrayOfString73 = new java.lang.String[3];
    arrayOfString73[0] = "&egrave;";
    arrayOfString73[1] = "&#232;";
    arrayOfString73[2] = "è";
    arrayOfString;[72] = arrayOfString73;
    java.lang.String[] arrayOfString74 = new java.lang.String[3];
    arrayOfString74[0] = "&eacute;";
    arrayOfString74[1] = "&#233;";
    arrayOfString74[2] = "é";
    arrayOfString;[73] = arrayOfString74;
    java.lang.String[] arrayOfString75 = new java.lang.String[3];
    arrayOfString75[0] = "&ecirc;";
    arrayOfString75[1] = "&#234;";
    arrayOfString75[2] = "ê";
    arrayOfString;[74] = arrayOfString75;
    java.lang.String[] arrayOfString76 = new java.lang.String[3];
    arrayOfString76[0] = "&euml;";
    arrayOfString76[1] = "&#235;";
    arrayOfString76[2] = "ë";
    arrayOfString;[75] = arrayOfString76;
    java.lang.String[] arrayOfString77 = new java.lang.String[3];
    arrayOfString77[0] = "&igrave;";
    arrayOfString77[1] = "&#236;";
    arrayOfString77[2] = "ì";
    arrayOfString;[76] = arrayOfString77;
    java.lang.String[] arrayOfString78 = new java.lang.String[3];
    arrayOfString78[0] = "&iacute;";
    arrayOfString78[1] = "&#237;";
    arrayOfString78[2] = "í";
    arrayOfString;[77] = arrayOfString78;
    java.lang.String[] arrayOfString79 = new java.lang.String[3];
    arrayOfString79[0] = "&icirc;";
    arrayOfString79[1] = "&#238;";
    arrayOfString79[2] = "î";
    arrayOfString;[78] = arrayOfString79;
    java.lang.String[] arrayOfString80 = new java.lang.String[3];
    arrayOfString80[0] = "&iuml;";
    arrayOfString80[1] = "&#239;";
    arrayOfString80[2] = "ï";
    arrayOfString;[79] = arrayOfString80;
    java.lang.String[] arrayOfString81 = new java.lang.String[3];
    arrayOfString81[0] = "&eth;";
    arrayOfString81[1] = "&#240;";
    arrayOfString81[2] = "ð";
    arrayOfString;[80] = arrayOfString81;
    java.lang.String[] arrayOfString82 = new java.lang.String[3];
    arrayOfString82[0] = "&ntilde;";
    arrayOfString82[1] = "&#241;";
    arrayOfString82[2] = "ñ";
    arrayOfString;[81] = arrayOfString82;
    java.lang.String[] arrayOfString83 = new java.lang.String[3];
    arrayOfString83[0] = "&ograve;";
    arrayOfString83[1] = "&#242;";
    arrayOfString83[2] = "ò";
    arrayOfString;[82] = arrayOfString83;
    java.lang.String[] arrayOfString84 = new java.lang.String[3];
    arrayOfString84[0] = "&oacute;";
    arrayOfString84[1] = "&#243;";
    arrayOfString84[2] = "ó";
    arrayOfString;[83] = arrayOfString84;
    java.lang.String[] arrayOfString85 = new java.lang.String[3];
    arrayOfString85[0] = "&ocirc;";
    arrayOfString85[1] = "&#244;";
    arrayOfString85[2] = "ô";
    arrayOfString;[84] = arrayOfString85;
    java.lang.String[] arrayOfString86 = new java.lang.String[3];
    arrayOfString86[0] = "&otilde;";
    arrayOfString86[1] = "&#245;";
    arrayOfString86[2] = "õ";
    arrayOfString;[85] = arrayOfString86;
    java.lang.String[] arrayOfString87 = new java.lang.String[3];
    arrayOfString87[0] = "&ouml;";
    arrayOfString87[1] = "&#246;";
    arrayOfString87[2] = "ö";
    arrayOfString;[86] = arrayOfString87;
    java.lang.String[] arrayOfString88 = new java.lang.String[3];
    arrayOfString88[0] = "&divide;";
    arrayOfString88[1] = "&#247;";
    arrayOfString88[2] = "÷";
    arrayOfString;[87] = arrayOfString88;
    java.lang.String[] arrayOfString89 = new java.lang.String[3];
    arrayOfString89[0] = "&oslash;";
    arrayOfString89[1] = "&#248;";
    arrayOfString89[2] = "ø";
    arrayOfString;[88] = arrayOfString89;
    java.lang.String[] arrayOfString90 = new java.lang.String[3];
    arrayOfString90[0] = "&ugrave;";
    arrayOfString90[1] = "&#249;";
    arrayOfString90[2] = "ù";
    arrayOfString;[89] = arrayOfString90;
    java.lang.String[] arrayOfString91 = new java.lang.String[3];
    arrayOfString91[0] = "&uacute;";
    arrayOfString91[1] = "&#250;";
    arrayOfString91[2] = "ú";
    arrayOfString;[90] = arrayOfString91;
    java.lang.String[] arrayOfString92 = new java.lang.String[3];
    arrayOfString92[0] = "&ucirc;";
    arrayOfString92[1] = "&#251;";
    arrayOfString92[2] = "û";
    arrayOfString;[91] = arrayOfString92;
    java.lang.String[] arrayOfString93 = new java.lang.String[3];
    arrayOfString93[0] = "&uuml;";
    arrayOfString93[1] = "&#252;";
    arrayOfString93[2] = "ü";
    arrayOfString;[92] = arrayOfString93;
    java.lang.String[] arrayOfString94 = new java.lang.String[3];
    arrayOfString94[0] = "&yacute;";
    arrayOfString94[1] = "&#253;";
    arrayOfString94[2] = "ý";
    arrayOfString;[93] = arrayOfString94;
    java.lang.String[] arrayOfString95 = new java.lang.String[3];
    arrayOfString95[0] = "&thorn;";
    arrayOfString95[1] = "&#254;";
    arrayOfString95[2] = "þ";
    arrayOfString;[94] = arrayOfString95;
    java.lang.String[] arrayOfString96 = new java.lang.String[3];
    arrayOfString96[0] = "&yuml;";
    arrayOfString96[1] = "&#255;";
    arrayOfString96[2] = "ÿ";
    arrayOfString;[95] = arrayOfString96;
    java.lang.String[] arrayOfString97 = new java.lang.String[3];
    arrayOfString97[0] = "&fnof;";
    arrayOfString97[1] = "&#402;";
    arrayOfString97[2] = "ƒ";
    arrayOfString;[96] = arrayOfString97;
    java.lang.String[] arrayOfString98 = new java.lang.String[3];
    arrayOfString98[0] = "&Alpha;";
    arrayOfString98[1] = "&#913;";
    arrayOfString98[2] = "Α";
    arrayOfString;[97] = arrayOfString98;
    java.lang.String[] arrayOfString99 = new java.lang.String[3];
    arrayOfString99[0] = "&Beta;";
    arrayOfString99[1] = "&#914;";
    arrayOfString99[2] = "Β";
    arrayOfString;[98] = arrayOfString99;
    java.lang.String[] arrayOfString100 = new java.lang.String[3];
    arrayOfString100[0] = "&Gamma;";
    arrayOfString100[1] = "&#915;";
    arrayOfString100[2] = "Γ";
    arrayOfString;[99] = arrayOfString100;
    java.lang.String[] arrayOfString101 = new java.lang.String[3];
    arrayOfString101[0] = "&Delta;";
    arrayOfString101[1] = "&#916;";
    arrayOfString101[2] = "Δ";
    arrayOfString;[100] = arrayOfString101;
    java.lang.String[] arrayOfString102 = new java.lang.String[3];
    arrayOfString102[0] = "&Epsilon;";
    arrayOfString102[1] = "&#917;";
    arrayOfString102[2] = "Ε";
    arrayOfString;[101] = arrayOfString102;
    java.lang.String[] arrayOfString103 = new java.lang.String[3];
    arrayOfString103[0] = "&Zeta;";
    arrayOfString103[1] = "&#918;";
    arrayOfString103[2] = "Ζ";
    arrayOfString;[102] = arrayOfString103;
    java.lang.String[] arrayOfString104 = new java.lang.String[3];
    arrayOfString104[0] = "&Eta;";
    arrayOfString104[1] = "&#919;";
    arrayOfString104[2] = "Η";
    arrayOfString;[103] = arrayOfString104;
    java.lang.String[] arrayOfString105 = new java.lang.String[3];
    arrayOfString105[0] = "&Theta;";
    arrayOfString105[1] = "&#920;";
    arrayOfString105[2] = "Θ";
    arrayOfString;[104] = arrayOfString105;
    java.lang.String[] arrayOfString106 = new java.lang.String[3];
    arrayOfString106[0] = "&Iota;";
    arrayOfString106[1] = "&#921;";
    arrayOfString106[2] = "Ι";
    arrayOfString;[105] = arrayOfString106;
    java.lang.String[] arrayOfString107 = new java.lang.String[3];
    arrayOfString107[0] = "&Kappa;";
    arrayOfString107[1] = "&#922;";
    arrayOfString107[2] = "Κ";
    arrayOfString;[106] = arrayOfString107;
    java.lang.String[] arrayOfString108 = new java.lang.String[3];
    arrayOfString108[0] = "&Lambda;";
    arrayOfString108[1] = "&#923;";
    arrayOfString108[2] = "Λ";
    arrayOfString;[107] = arrayOfString108;
    java.lang.String[] arrayOfString109 = new java.lang.String[3];
    arrayOfString109[0] = "&Mu;";
    arrayOfString109[1] = "&#924;";
    arrayOfString109[2] = "Μ";
    arrayOfString;[108] = arrayOfString109;
    java.lang.String[] arrayOfString110 = new java.lang.String[3];
    arrayOfString110[0] = "&Nu;";
    arrayOfString110[1] = "&#925;";
    arrayOfString110[2] = "Ν";
    arrayOfString;[109] = arrayOfString110;
    java.lang.String[] arrayOfString111 = new java.lang.String[3];
    arrayOfString111[0] = "&Xi;";
    arrayOfString111[1] = "&#926;";
    arrayOfString111[2] = "Ξ";
    arrayOfString;[110] = arrayOfString111;
    java.lang.String[] arrayOfString112 = new java.lang.String[3];
    arrayOfString112[0] = "&Omicron;";
    arrayOfString112[1] = "&#927;";
    arrayOfString112[2] = "Ο";
    arrayOfString;[111] = arrayOfString112;
    java.lang.String[] arrayOfString113 = new java.lang.String[3];
    arrayOfString113[0] = "&Pi;";
    arrayOfString113[1] = "&#928;";
    arrayOfString113[2] = "Π";
    arrayOfString;[112] = arrayOfString113;
    java.lang.String[] arrayOfString114 = new java.lang.String[3];
    arrayOfString114[0] = "&Rho;";
    arrayOfString114[1] = "&#929;";
    arrayOfString114[2] = "Ρ";
    arrayOfString;[113] = arrayOfString114;
    java.lang.String[] arrayOfString115 = new java.lang.String[3];
    arrayOfString115[0] = "&Sigma;";
    arrayOfString115[1] = "&#931;";
    arrayOfString115[2] = "Σ";
    arrayOfString;[114] = arrayOfString115;
    java.lang.String[] arrayOfString116 = new java.lang.String[3];
    arrayOfString116[0] = "&Tau;";
    arrayOfString116[1] = "&#932;";
    arrayOfString116[2] = "Τ";
    arrayOfString;[115] = arrayOfString116;
    java.lang.String[] arrayOfString117 = new java.lang.String[3];
    arrayOfString117[0] = "&Upsilon;";
    arrayOfString117[1] = "&#933;";
    arrayOfString117[2] = "Υ";
    arrayOfString;[116] = arrayOfString117;
    java.lang.String[] arrayOfString118 = new java.lang.String[3];
    arrayOfString118[0] = "&Phi;";
    arrayOfString118[1] = "&#934;";
    arrayOfString118[2] = "Φ";
    arrayOfString;[117] = arrayOfString118;
    java.lang.String[] arrayOfString119 = new java.lang.String[3];
    arrayOfString119[0] = "&Chi;";
    arrayOfString119[1] = "&#935;";
    arrayOfString119[2] = "Χ";
    arrayOfString;[118] = arrayOfString119;
    java.lang.String[] arrayOfString120 = new java.lang.String[3];
    arrayOfString120[0] = "&Psi;";
    arrayOfString120[1] = "&#936;";
    arrayOfString120[2] = "Ψ";
    arrayOfString;[119] = arrayOfString120;
    java.lang.String[] arrayOfString121 = new java.lang.String[3];
    arrayOfString121[0] = "&Omega;";
    arrayOfString121[1] = "&#937;";
    arrayOfString121[2] = "Ω";
    arrayOfString;[120] = arrayOfString121;
    java.lang.String[] arrayOfString122 = new java.lang.String[3];
    arrayOfString122[0] = "&alpha;";
    arrayOfString122[1] = "&#945;";
    arrayOfString122[2] = "α";
    arrayOfString;[121] = arrayOfString122;
    java.lang.String[] arrayOfString123 = new java.lang.String[3];
    arrayOfString123[0] = "&beta;";
    arrayOfString123[1] = "&#946;";
    arrayOfString123[2] = "β";
    arrayOfString;[122] = arrayOfString123;
    java.lang.String[] arrayOfString124 = new java.lang.String[3];
    arrayOfString124[0] = "&gamma;";
    arrayOfString124[1] = "&#947;";
    arrayOfString124[2] = "γ";
    arrayOfString;[123] = arrayOfString124;
    java.lang.String[] arrayOfString125 = new java.lang.String[3];
    arrayOfString125[0] = "&delta;";
    arrayOfString125[1] = "&#948;";
    arrayOfString125[2] = "δ";
    arrayOfString;[124] = arrayOfString125;
    java.lang.String[] arrayOfString126 = new java.lang.String[3];
    arrayOfString126[0] = "&epsilon;";
    arrayOfString126[1] = "&#949;";
    arrayOfString126[2] = "ε";
    arrayOfString;[125] = arrayOfString126;
    java.lang.String[] arrayOfString127 = new java.lang.String[3];
    arrayOfString127[0] = "&zeta;";
    arrayOfString127[1] = "&#950;";
    arrayOfString127[2] = "ζ";
    arrayOfString;[126] = arrayOfString127;
    java.lang.String[] arrayOfString128 = new java.lang.String[3];
    arrayOfString128[0] = "&eta;";
    arrayOfString128[1] = "&#951;";
    arrayOfString128[2] = "η";
    arrayOfString;[127] = arrayOfString128;
    java.lang.String[] arrayOfString129 = new java.lang.String[3];
    arrayOfString129[0] = "&theta;";
    arrayOfString129[1] = "&#952;";
    arrayOfString129[2] = "θ";
    arrayOfString;[''] = arrayOfString129;
    java.lang.String[] arrayOfString130 = new java.lang.String[3];
    arrayOfString130[0] = "&iota;";
    arrayOfString130[1] = "&#953;";
    arrayOfString130[2] = "ι";
    arrayOfString;[''] = arrayOfString130;
    java.lang.String[] arrayOfString131 = new java.lang.String[3];
    arrayOfString131[0] = "&kappa;";
    arrayOfString131[1] = "&#954;";
    arrayOfString131[2] = "κ";
    arrayOfString;[''] = arrayOfString131;
    java.lang.String[] arrayOfString132 = new java.lang.String[3];
    arrayOfString132[0] = "&lambda;";
    arrayOfString132[1] = "&#955;";
    arrayOfString132[2] = "λ";
    arrayOfString;[''] = arrayOfString132;
    java.lang.String[] arrayOfString133 = new java.lang.String[3];
    arrayOfString133[0] = "&mu;";
    arrayOfString133[1] = "&#956;";
    arrayOfString133[2] = "μ";
    arrayOfString;[''] = arrayOfString133;
    java.lang.String[] arrayOfString134 = new java.lang.String[3];
    arrayOfString134[0] = "&nu;";
    arrayOfString134[1] = "&#957;";
    arrayOfString134[2] = "ν";
    arrayOfString;[''] = arrayOfString134;
    java.lang.String[] arrayOfString135 = new java.lang.String[3];
    arrayOfString135[0] = "&xi;";
    arrayOfString135[1] = "&#958;";
    arrayOfString135[2] = "ξ";
    arrayOfString;[''] = arrayOfString135;
    java.lang.String[] arrayOfString136 = new java.lang.String[3];
    arrayOfString136[0] = "&omicron;";
    arrayOfString136[1] = "&#959;";
    arrayOfString136[2] = "ο";
    arrayOfString;[''] = arrayOfString136;
    java.lang.String[] arrayOfString137 = new java.lang.String[3];
    arrayOfString137[0] = "&pi;";
    arrayOfString137[1] = "&#960;";
    arrayOfString137[2] = "π";
    arrayOfString;[''] = arrayOfString137;
    java.lang.String[] arrayOfString138 = new java.lang.String[3];
    arrayOfString138[0] = "&rho;";
    arrayOfString138[1] = "&#961;";
    arrayOfString138[2] = "ρ";
    arrayOfString;[''] = arrayOfString138;
    java.lang.String[] arrayOfString139 = new java.lang.String[3];
    arrayOfString139[0] = "&sigmaf;";
    arrayOfString139[1] = "&#962;";
    arrayOfString139[2] = "ς";
    arrayOfString;[''] = arrayOfString139;
    java.lang.String[] arrayOfString140 = new java.lang.String[3];
    arrayOfString140[0] = "&sigma;";
    arrayOfString140[1] = "&#963;";
    arrayOfString140[2] = "σ";
    arrayOfString;[''] = arrayOfString140;
    java.lang.String[] arrayOfString141 = new java.lang.String[3];
    arrayOfString141[0] = "&tau;";
    arrayOfString141[1] = "&#964;";
    arrayOfString141[2] = "τ";
    arrayOfString;[''] = arrayOfString141;
    java.lang.String[] arrayOfString142 = new java.lang.String[3];
    arrayOfString142[0] = "&upsilon;";
    arrayOfString142[1] = "&#965;";
    arrayOfString142[2] = "υ";
    arrayOfString;[''] = arrayOfString142;
    java.lang.String[] arrayOfString143 = new java.lang.String[3];
    arrayOfString143[0] = "&phi;";
    arrayOfString143[1] = "&#966;";
    arrayOfString143[2] = "φ";
    arrayOfString;[''] = arrayOfString143;
    java.lang.String[] arrayOfString144 = new java.lang.String[3];
    arrayOfString144[0] = "&chi;";
    arrayOfString144[1] = "&#967;";
    arrayOfString144[2] = "χ";
    arrayOfString;[''] = arrayOfString144;
    java.lang.String[] arrayOfString145 = new java.lang.String[3];
    arrayOfString145[0] = "&psi;";
    arrayOfString145[1] = "&#968;";
    arrayOfString145[2] = "ψ";
    arrayOfString;[''] = arrayOfString145;
    java.lang.String[] arrayOfString146 = new java.lang.String[3];
    arrayOfString146[0] = "&omega;";
    arrayOfString146[1] = "&#969;";
    arrayOfString146[2] = "ω";
    arrayOfString;[''] = arrayOfString146;
    java.lang.String[] arrayOfString147 = new java.lang.String[3];
    arrayOfString147[0] = "&thetasym;";
    arrayOfString147[1] = "&#977;";
    arrayOfString147[2] = "ϑ";
    arrayOfString;[''] = arrayOfString147;
    java.lang.String[] arrayOfString148 = new java.lang.String[3];
    arrayOfString148[0] = "&upsih;";
    arrayOfString148[1] = "&#978;";
    arrayOfString148[2] = "ϒ";
    arrayOfString;[''] = arrayOfString148;
    java.lang.String[] arrayOfString149 = new java.lang.String[3];
    arrayOfString149[0] = "&piv;";
    arrayOfString149[1] = "&#982;";
    arrayOfString149[2] = "ϖ";
    arrayOfString;[''] = arrayOfString149;
    java.lang.String[] arrayOfString150 = new java.lang.String[3];
    arrayOfString150[0] = "&bull;";
    arrayOfString150[1] = "&#8226;";
    arrayOfString150[2] = "•";
    arrayOfString;[''] = arrayOfString150;
    java.lang.String[] arrayOfString151 = new java.lang.String[3];
    arrayOfString151[0] = "&hellip;";
    arrayOfString151[1] = "&#8230;";
    arrayOfString151[2] = "…";
    arrayOfString;[''] = arrayOfString151;
    java.lang.String[] arrayOfString152 = new java.lang.String[3];
    arrayOfString152[0] = "&prime;";
    arrayOfString152[1] = "&#8242;";
    arrayOfString152[2] = "′";
    arrayOfString;[''] = arrayOfString152;
    java.lang.String[] arrayOfString153 = new java.lang.String[3];
    arrayOfString153[0] = "&Prime;";
    arrayOfString153[1] = "&#8243;";
    arrayOfString153[2] = "″";
    arrayOfString;[''] = arrayOfString153;
    java.lang.String[] arrayOfString154 = new java.lang.String[3];
    arrayOfString154[0] = "&oline;";
    arrayOfString154[1] = "&#8254;";
    arrayOfString154[2] = "‾";
    arrayOfString;[''] = arrayOfString154;
    java.lang.String[] arrayOfString155 = new java.lang.String[3];
    arrayOfString155[0] = "&frasl;";
    arrayOfString155[1] = "&#8260;";
    arrayOfString155[2] = "⁄";
    arrayOfString;[''] = arrayOfString155;
    java.lang.String[] arrayOfString156 = new java.lang.String[3];
    arrayOfString156[0] = "&weierp;";
    arrayOfString156[1] = "&#8472;";
    arrayOfString156[2] = "℘";
    arrayOfString;[''] = arrayOfString156;
    java.lang.String[] arrayOfString157 = new java.lang.String[3];
    arrayOfString157[0] = "&image;";
    arrayOfString157[1] = "&#8465;";
    arrayOfString157[2] = "ℑ";
    arrayOfString;[''] = arrayOfString157;
    java.lang.String[] arrayOfString158 = new java.lang.String[3];
    arrayOfString158[0] = "&real;";
    arrayOfString158[1] = "&#8476;";
    arrayOfString158[2] = "ℜ";
    arrayOfString;[''] = arrayOfString158;
    java.lang.String[] arrayOfString159 = new java.lang.String[3];
    arrayOfString159[0] = "&trade;";
    arrayOfString159[1] = "&#8482;";
    arrayOfString159[2] = "™";
    arrayOfString;[''] = arrayOfString159;
    java.lang.String[] arrayOfString160 = new java.lang.String[3];
    arrayOfString160[0] = "&alefsym;";
    arrayOfString160[1] = "&#8501;";
    arrayOfString160[2] = "ℵ";
    arrayOfString;[''] = arrayOfString160;
    java.lang.String[] arrayOfString161 = new java.lang.String[3];
    arrayOfString161[0] = "&larr;";
    arrayOfString161[1] = "&#8592;";
    arrayOfString161[2] = "←";
    arrayOfString;[' '] = arrayOfString161;
    java.lang.String[] arrayOfString162 = new java.lang.String[3];
    arrayOfString162[0] = "&uarr;";
    arrayOfString162[1] = "&#8593;";
    arrayOfString162[2] = "↑";
    arrayOfString;['¡'] = arrayOfString162;
    java.lang.String[] arrayOfString163 = new java.lang.String[3];
    arrayOfString163[0] = "&rarr;";
    arrayOfString163[1] = "&#8594;";
    arrayOfString163[2] = "→";
    arrayOfString;['¢'] = arrayOfString163;
    java.lang.String[] arrayOfString164 = new java.lang.String[3];
    arrayOfString164[0] = "&darr;";
    arrayOfString164[1] = "&#8595;";
    arrayOfString164[2] = "↓";
    arrayOfString;['£'] = arrayOfString164;
    java.lang.String[] arrayOfString165 = new java.lang.String[3];
    arrayOfString165[0] = "&harr;";
    arrayOfString165[1] = "&#8596;";
    arrayOfString165[2] = "↔";
    arrayOfString;['¤'] = arrayOfString165;
    java.lang.String[] arrayOfString166 = new java.lang.String[3];
    arrayOfString166[0] = "&crarr;";
    arrayOfString166[1] = "&#8629;";
    arrayOfString166[2] = "↵";
    arrayOfString;['¥'] = arrayOfString166;
    java.lang.String[] arrayOfString167 = new java.lang.String[3];
    arrayOfString167[0] = "&lArr;";
    arrayOfString167[1] = "&#8656;";
    arrayOfString167[2] = "⇐";
    arrayOfString;['¦'] = arrayOfString167;
    java.lang.String[] arrayOfString168 = new java.lang.String[3];
    arrayOfString168[0] = "&uArr;";
    arrayOfString168[1] = "&#8657;";
    arrayOfString168[2] = "⇑";
    arrayOfString;['§'] = arrayOfString168;
    java.lang.String[] arrayOfString169 = new java.lang.String[3];
    arrayOfString169[0] = "&rArr;";
    arrayOfString169[1] = "&#8658;";
    arrayOfString169[2] = "⇒";
    arrayOfString;['¨'] = arrayOfString169;
    java.lang.String[] arrayOfString170 = new java.lang.String[3];
    arrayOfString170[0] = "&dArr;";
    arrayOfString170[1] = "&#8659;";
    arrayOfString170[2] = "⇓";
    arrayOfString;['©'] = arrayOfString170;
    java.lang.String[] arrayOfString171 = new java.lang.String[3];
    arrayOfString171[0] = "&hArr;";
    arrayOfString171[1] = "&#8660;";
    arrayOfString171[2] = "⇔";
    arrayOfString;['ª'] = arrayOfString171;
    java.lang.String[] arrayOfString172 = new java.lang.String[3];
    arrayOfString172[0] = "&forall;";
    arrayOfString172[1] = "&#8704;";
    arrayOfString172[2] = "∀";
    arrayOfString;['«'] = arrayOfString172;
    java.lang.String[] arrayOfString173 = new java.lang.String[3];
    arrayOfString173[0] = "&part;";
    arrayOfString173[1] = "&#8706;";
    arrayOfString173[2] = "∂";
    arrayOfString;['¬'] = arrayOfString173;
    java.lang.String[] arrayOfString174 = new java.lang.String[3];
    arrayOfString174[0] = "&exist;";
    arrayOfString174[1] = "&#8707;";
    arrayOfString174[2] = "∃";
    arrayOfString;['­'] = arrayOfString174;
    java.lang.String[] arrayOfString175 = new java.lang.String[3];
    arrayOfString175[0] = "&empty;";
    arrayOfString175[1] = "&#8709;";
    arrayOfString175[2] = "∅";
    arrayOfString;['®'] = arrayOfString175;
    java.lang.String[] arrayOfString176 = new java.lang.String[3];
    arrayOfString176[0] = "&nabla;";
    arrayOfString176[1] = "&#8711;";
    arrayOfString176[2] = "∇";
    arrayOfString;['¯'] = arrayOfString176;
    java.lang.String[] arrayOfString177 = new java.lang.String[3];
    arrayOfString177[0] = "&isin;";
    arrayOfString177[1] = "&#8712;";
    arrayOfString177[2] = "∈";
    arrayOfString;['°'] = arrayOfString177;
    java.lang.String[] arrayOfString178 = new java.lang.String[3];
    arrayOfString178[0] = "&notin;";
    arrayOfString178[1] = "&#8713;";
    arrayOfString178[2] = "∉";
    arrayOfString;['±'] = arrayOfString178;
    java.lang.String[] arrayOfString179 = new java.lang.String[3];
    arrayOfString179[0] = "&ni;";
    arrayOfString179[1] = "&#8715;";
    arrayOfString179[2] = "∋";
    arrayOfString;['²'] = arrayOfString179;
    java.lang.String[] arrayOfString180 = new java.lang.String[3];
    arrayOfString180[0] = "&prod;";
    arrayOfString180[1] = "&#8719;";
    arrayOfString180[2] = "∏";
    arrayOfString;['³'] = arrayOfString180;
    java.lang.String[] arrayOfString181 = new java.lang.String[3];
    arrayOfString181[0] = "&sum;";
    arrayOfString181[1] = "&#8721;";
    arrayOfString181[2] = "∑";
    arrayOfString;['´'] = arrayOfString181;
    java.lang.String[] arrayOfString182 = new java.lang.String[3];
    arrayOfString182[0] = "&minus;";
    arrayOfString182[1] = "&#8722;";
    arrayOfString182[2] = "−";
    arrayOfString;['µ'] = arrayOfString182;
    java.lang.String[] arrayOfString183 = new java.lang.String[3];
    arrayOfString183[0] = "&lowast;";
    arrayOfString183[1] = "&#8727;";
    arrayOfString183[2] = "∗";
    arrayOfString;['¶'] = arrayOfString183;
    java.lang.String[] arrayOfString184 = new java.lang.String[3];
    arrayOfString184[0] = "&radic;";
    arrayOfString184[1] = "&#8730;";
    arrayOfString184[2] = "√";
    arrayOfString;['·'] = arrayOfString184;
    java.lang.String[] arrayOfString185 = new java.lang.String[3];
    arrayOfString185[0] = "&prop;";
    arrayOfString185[1] = "&#8733;";
    arrayOfString185[2] = "∝";
    arrayOfString;['¸'] = arrayOfString185;
    java.lang.String[] arrayOfString186 = new java.lang.String[3];
    arrayOfString186[0] = "&infin;";
    arrayOfString186[1] = "&#8734;";
    arrayOfString186[2] = "∞";
    arrayOfString;['¹'] = arrayOfString186;
    java.lang.String[] arrayOfString187 = new java.lang.String[3];
    arrayOfString187[0] = "&ang;";
    arrayOfString187[1] = "&#8736;";
    arrayOfString187[2] = "∠";
    arrayOfString;['º'] = arrayOfString187;
    java.lang.String[] arrayOfString188 = new java.lang.String[3];
    arrayOfString188[0] = "&and;";
    arrayOfString188[1] = "&#8743;";
    arrayOfString188[2] = "∧";
    arrayOfString;['»'] = arrayOfString188;
    java.lang.String[] arrayOfString189 = new java.lang.String[3];
    arrayOfString189[0] = "&or;";
    arrayOfString189[1] = "&#8744;";
    arrayOfString189[2] = "∨";
    arrayOfString;['¼'] = arrayOfString189;
    java.lang.String[] arrayOfString190 = new java.lang.String[3];
    arrayOfString190[0] = "&cap;";
    arrayOfString190[1] = "&#8745;";
    arrayOfString190[2] = "∩";
    arrayOfString;['½'] = arrayOfString190;
    java.lang.String[] arrayOfString191 = new java.lang.String[3];
    arrayOfString191[0] = "&cup;";
    arrayOfString191[1] = "&#8746;";
    arrayOfString191[2] = "∪";
    arrayOfString;['¾'] = arrayOfString191;
    java.lang.String[] arrayOfString192 = new java.lang.String[3];
    arrayOfString192[0] = "&int;";
    arrayOfString192[1] = "&#8747;";
    arrayOfString192[2] = "∫";
    arrayOfString;['¿'] = arrayOfString192;
    java.lang.String[] arrayOfString193 = new java.lang.String[3];
    arrayOfString193[0] = "&there4;";
    arrayOfString193[1] = "&#8756;";
    arrayOfString193[2] = "∴";
    arrayOfString;['À'] = arrayOfString193;
    java.lang.String[] arrayOfString194 = new java.lang.String[3];
    arrayOfString194[0] = "&sim;";
    arrayOfString194[1] = "&#8764;";
    arrayOfString194[2] = "∼";
    arrayOfString;['Á'] = arrayOfString194;
    java.lang.String[] arrayOfString195 = new java.lang.String[3];
    arrayOfString195[0] = "&cong;";
    arrayOfString195[1] = "&#8773;";
    arrayOfString195[2] = "≅";
    arrayOfString;['Â'] = arrayOfString195;
    java.lang.String[] arrayOfString196 = new java.lang.String[3];
    arrayOfString196[0] = "&asymp;";
    arrayOfString196[1] = "&#8776;";
    arrayOfString196[2] = "≈";
    arrayOfString;['Ã'] = arrayOfString196;
    java.lang.String[] arrayOfString197 = new java.lang.String[3];
    arrayOfString197[0] = "&ne;";
    arrayOfString197[1] = "&#8800;";
    arrayOfString197[2] = "≠";
    arrayOfString;['Ä'] = arrayOfString197;
    java.lang.String[] arrayOfString198 = new java.lang.String[3];
    arrayOfString198[0] = "&equiv;";
    arrayOfString198[1] = "&#8801;";
    arrayOfString198[2] = "≡";
    arrayOfString;['Å'] = arrayOfString198;
    java.lang.String[] arrayOfString199 = new java.lang.String[3];
    arrayOfString199[0] = "&le;";
    arrayOfString199[1] = "&#8804;";
    arrayOfString199[2] = "≤";
    arrayOfString;['Æ'] = arrayOfString199;
    java.lang.String[] arrayOfString200 = new java.lang.String[3];
    arrayOfString200[0] = "&ge;";
    arrayOfString200[1] = "&#8805;";
    arrayOfString200[2] = "≥";
    arrayOfString;['Ç'] = arrayOfString200;
    java.lang.String[] arrayOfString201 = new java.lang.String[3];
    arrayOfString201[0] = "&sub;";
    arrayOfString201[1] = "&#8834;";
    arrayOfString201[2] = "⊂";
    arrayOfString;['È'] = arrayOfString201;
    java.lang.String[] arrayOfString202 = new java.lang.String[3];
    arrayOfString202[0] = "&sup;";
    arrayOfString202[1] = "&#8835;";
    arrayOfString202[2] = "⊃";
    arrayOfString;['É'] = arrayOfString202;
    java.lang.String[] arrayOfString203 = new java.lang.String[3];
    arrayOfString203[0] = "&sube;";
    arrayOfString203[1] = "&#8838;";
    arrayOfString203[2] = "⊆";
    arrayOfString;['Ê'] = arrayOfString203;
    java.lang.String[] arrayOfString204 = new java.lang.String[3];
    arrayOfString204[0] = "&supe;";
    arrayOfString204[1] = "&#8839;";
    arrayOfString204[2] = "⊇";
    arrayOfString;['Ë'] = arrayOfString204;
    java.lang.String[] arrayOfString205 = new java.lang.String[3];
    arrayOfString205[0] = "&oplus;";
    arrayOfString205[1] = "&#8853;";
    arrayOfString205[2] = "⊕";
    arrayOfString;['Ì'] = arrayOfString205;
    java.lang.String[] arrayOfString206 = new java.lang.String[3];
    arrayOfString206[0] = "&otimes;";
    arrayOfString206[1] = "&#8855;";
    arrayOfString206[2] = "⊗";
    arrayOfString;['Í'] = arrayOfString206;
    java.lang.String[] arrayOfString207 = new java.lang.String[3];
    arrayOfString207[0] = "&perp;";
    arrayOfString207[1] = "&#8869;";
    arrayOfString207[2] = "⊥";
    arrayOfString;['Î'] = arrayOfString207;
    java.lang.String[] arrayOfString208 = new java.lang.String[3];
    arrayOfString208[0] = "&sdot;";
    arrayOfString208[1] = "&#8901;";
    arrayOfString208[2] = "⋅";
    arrayOfString;['Ï'] = arrayOfString208;
    java.lang.String[] arrayOfString209 = new java.lang.String[3];
    arrayOfString209[0] = "&lceil;";
    arrayOfString209[1] = "&#8968;";
    arrayOfString209[2] = "⌈";
    arrayOfString;['Ð'] = arrayOfString209;
    java.lang.String[] arrayOfString210 = new java.lang.String[3];
    arrayOfString210[0] = "&rceil;";
    arrayOfString210[1] = "&#8969;";
    arrayOfString210[2] = "⌉";
    arrayOfString;['Ñ'] = arrayOfString210;
    java.lang.String[] arrayOfString211 = new java.lang.String[3];
    arrayOfString211[0] = "&lfloor;";
    arrayOfString211[1] = "&#8970;";
    arrayOfString211[2] = "⌊";
    arrayOfString;['Ò'] = arrayOfString211;
    java.lang.String[] arrayOfString212 = new java.lang.String[3];
    arrayOfString212[0] = "&rfloor;";
    arrayOfString212[1] = "&#8971;";
    arrayOfString212[2] = "⌋";
    arrayOfString;['Ó'] = arrayOfString212;
    java.lang.String[] arrayOfString213 = new java.lang.String[3];
    arrayOfString213[0] = "&lang;";
    arrayOfString213[1] = "&#9001;";
    arrayOfString213[2] = "〈";
    arrayOfString;['Ô'] = arrayOfString213;
    java.lang.String[] arrayOfString214 = new java.lang.String[3];
    arrayOfString214[0] = "&rang;";
    arrayOfString214[1] = "&#9002;";
    arrayOfString214[2] = "〉";
    arrayOfString;['Õ'] = arrayOfString214;
    java.lang.String[] arrayOfString215 = new java.lang.String[3];
    arrayOfString215[0] = "&loz;";
    arrayOfString215[1] = "&#9674;";
    arrayOfString215[2] = "◊";
    arrayOfString;['Ö'] = arrayOfString215;
    java.lang.String[] arrayOfString216 = new java.lang.String[3];
    arrayOfString216[0] = "&spades;";
    arrayOfString216[1] = "&#9824;";
    arrayOfString216[2] = "♠";
    arrayOfString;['×'] = arrayOfString216;
    java.lang.String[] arrayOfString217 = new java.lang.String[3];
    arrayOfString217[0] = "&clubs;";
    arrayOfString217[1] = "&#9827;";
    arrayOfString217[2] = "♣";
    arrayOfString;['Ø'] = arrayOfString217;
    java.lang.String[] arrayOfString218 = new java.lang.String[3];
    arrayOfString218[0] = "&hearts;";
    arrayOfString218[1] = "&#9829;";
    arrayOfString218[2] = "♥";
    arrayOfString;['Ù'] = arrayOfString218;
    java.lang.String[] arrayOfString219 = new java.lang.String[3];
    arrayOfString219[0] = "&diams;";
    arrayOfString219[1] = "&#9830;";
    arrayOfString219[2] = "♦";
    arrayOfString;['Ú'] = arrayOfString219;
    java.lang.String[] arrayOfString220 = new java.lang.String[3];
    arrayOfString220[0] = "&quot;";
    arrayOfString220[1] = "&#34;";
    arrayOfString220[2] = "\"";
    arrayOfString;['Û'] = arrayOfString220;
    java.lang.String[] arrayOfString221 = new java.lang.String[3];
    arrayOfString221[0] = "&amp;";
    arrayOfString221[1] = "&#38;";
    arrayOfString221[2] = "&";
    arrayOfString;['Ü'] = arrayOfString221;
    java.lang.String[] arrayOfString222 = new java.lang.String[3];
    arrayOfString222[0] = "&lt;";
    arrayOfString222[1] = "&#60;";
    arrayOfString222[2] = "<";
    arrayOfString;['Ý'] = arrayOfString222;
    java.lang.String[] arrayOfString223 = new java.lang.String[3];
    arrayOfString223[0] = "&gt;";
    arrayOfString223[1] = "&#62;";
    arrayOfString223[2] = ">";
    arrayOfString;['Þ'] = arrayOfString223;
    java.lang.String[] arrayOfString224 = new java.lang.String[3];
    arrayOfString224[0] = "&OElig;";
    arrayOfString224[1] = "&#338;";
    arrayOfString224[2] = "Œ";
    arrayOfString;['ß'] = arrayOfString224;
    java.lang.String[] arrayOfString225 = new java.lang.String[3];
    arrayOfString225[0] = "&oelig;";
    arrayOfString225[1] = "&#339;";
    arrayOfString225[2] = "œ";
    arrayOfString;['à'] = arrayOfString225;
    java.lang.String[] arrayOfString226 = new java.lang.String[3];
    arrayOfString226[0] = "&Scaron;";
    arrayOfString226[1] = "&#352;";
    arrayOfString226[2] = "Š";
    arrayOfString;['á'] = arrayOfString226;
    java.lang.String[] arrayOfString227 = new java.lang.String[3];
    arrayOfString227[0] = "&scaron;";
    arrayOfString227[1] = "&#353;";
    arrayOfString227[2] = "š";
    arrayOfString;['â'] = arrayOfString227;
    java.lang.String[] arrayOfString228 = new java.lang.String[3];
    arrayOfString228[0] = "&Yuml;";
    arrayOfString228[1] = "&#376;";
    arrayOfString228[2] = "Ÿ";
    arrayOfString;['ã'] = arrayOfString228;
    java.lang.String[] arrayOfString229 = new java.lang.String[3];
    arrayOfString229[0] = "&circ;";
    arrayOfString229[1] = "&#710;";
    arrayOfString229[2] = "ˆ";
    arrayOfString;['ä'] = arrayOfString229;
    java.lang.String[] arrayOfString230 = new java.lang.String[3];
    arrayOfString230[0] = "&tilde;";
    arrayOfString230[1] = "&#732;";
    arrayOfString230[2] = "˜";
    arrayOfString;['å'] = arrayOfString230;
    java.lang.String[] arrayOfString231 = new java.lang.String[3];
    arrayOfString231[0] = "&ensp;";
    arrayOfString231[1] = "&#8194;";
    arrayOfString231[2] = " ";
    arrayOfString;['æ'] = arrayOfString231;
    java.lang.String[] arrayOfString232 = new java.lang.String[3];
    arrayOfString232[0] = "&emsp;";
    arrayOfString232[1] = "&#8195;";
    arrayOfString232[2] = " ";
    arrayOfString;['ç'] = arrayOfString232;
    java.lang.String[] arrayOfString233 = new java.lang.String[3];
    arrayOfString233[0] = "&thinsp;";
    arrayOfString233[1] = "&#8201;";
    arrayOfString233[2] = " ";
    arrayOfString;['è'] = arrayOfString233;
    java.lang.String[] arrayOfString234 = new java.lang.String[3];
    arrayOfString234[0] = "&zwnj;";
    arrayOfString234[1] = "&#8204;";
    arrayOfString234[2] = "‌";
    arrayOfString;['é'] = arrayOfString234;
    java.lang.String[] arrayOfString235 = new java.lang.String[3];
    arrayOfString235[0] = "&zwj;";
    arrayOfString235[1] = "&#8205;";
    arrayOfString235[2] = "‍";
    arrayOfString;['ê'] = arrayOfString235;
    java.lang.String[] arrayOfString236 = new java.lang.String[3];
    arrayOfString236[0] = "&lrm;";
    arrayOfString236[1] = "&#8206;";
    arrayOfString236[2] = "‎";
    arrayOfString;['ë'] = arrayOfString236;
    java.lang.String[] arrayOfString237 = new java.lang.String[3];
    arrayOfString237[0] = "&rlm;";
    arrayOfString237[1] = "&#8207;";
    arrayOfString237[2] = "‏";
    arrayOfString;['ì'] = arrayOfString237;
    java.lang.String[] arrayOfString238 = new java.lang.String[3];
    arrayOfString238[0] = "&ndash;";
    arrayOfString238[1] = "&#8211;";
    arrayOfString238[2] = "–";
    arrayOfString;['í'] = arrayOfString238;
    java.lang.String[] arrayOfString239 = new java.lang.String[3];
    arrayOfString239[0] = "&mdash;";
    arrayOfString239[1] = "&#8212;";
    arrayOfString239[2] = "—";
    arrayOfString;['î'] = arrayOfString239;
    java.lang.String[] arrayOfString240 = new java.lang.String[3];
    arrayOfString240[0] = "&lsquo;";
    arrayOfString240[1] = "&#8216;";
    arrayOfString240[2] = "‘";
    arrayOfString;['ï'] = arrayOfString240;
    java.lang.String[] arrayOfString241 = new java.lang.String[3];
    arrayOfString241[0] = "&rsquo;";
    arrayOfString241[1] = "&#8217;";
    arrayOfString241[2] = "’";
    arrayOfString;['ð'] = arrayOfString241;
    java.lang.String[] arrayOfString242 = new java.lang.String[3];
    arrayOfString242[0] = "&sbquo;";
    arrayOfString242[1] = "&#8218;";
    arrayOfString242[2] = "‚";
    arrayOfString;['ñ'] = arrayOfString242;
    java.lang.String[] arrayOfString243 = new java.lang.String[3];
    arrayOfString243[0] = "&ldquo;";
    arrayOfString243[1] = "&#8220;";
    arrayOfString243[2] = "“";
    arrayOfString;['ò'] = arrayOfString243;
    java.lang.String[] arrayOfString244 = new java.lang.String[3];
    arrayOfString244[0] = "&rdquo;";
    arrayOfString244[1] = "&#8221;";
    arrayOfString244[2] = "”";
    arrayOfString;['ó'] = arrayOfString244;
    java.lang.String[] arrayOfString245 = new java.lang.String[3];
    arrayOfString245[0] = "&bdquo;";
    arrayOfString245[1] = "&#8222;";
    arrayOfString245[2] = "„";
    arrayOfString;['ô'] = arrayOfString245;
    java.lang.String[] arrayOfString246 = new java.lang.String[3];
    arrayOfString246[0] = "&dagger;";
    arrayOfString246[1] = "&#8224;";
    arrayOfString246[2] = "†";
    arrayOfString;['õ'] = arrayOfString246;
    java.lang.String[] arrayOfString247 = new java.lang.String[3];
    arrayOfString247[0] = "&Dagger;";
    arrayOfString247[1] = "&#8225;";
    arrayOfString247[2] = "‡";
    arrayOfString;['ö'] = arrayOfString247;
    java.lang.String[] arrayOfString248 = new java.lang.String[3];
    arrayOfString248[0] = "&permil;";
    arrayOfString248[1] = "&#8240;";
    arrayOfString248[2] = "‰";
    arrayOfString;['÷'] = arrayOfString248;
    java.lang.String[] arrayOfString249 = new java.lang.String[3];
    arrayOfString249[0] = "&lsaquo;";
    arrayOfString249[1] = "&#8249;";
    arrayOfString249[2] = "‹";
    arrayOfString;['ø'] = arrayOfString249;
    java.lang.String[] arrayOfString250 = new java.lang.String[3];
    arrayOfString250[0] = "&rsaquo;";
    arrayOfString250[1] = "&#8250;";
    arrayOfString250[2] = "›";
    arrayOfString;['ù'] = arrayOfString250;
    java.lang.String[] arrayOfString251 = new java.lang.String[3];
    arrayOfString251[0] = "&euro;";
    arrayOfString251[1] = "&#8364;";
    arrayOfString251[2] = "€";
    arrayOfString;['ú'] = arrayOfString251;
    int i = arrayOfString;.length;
    for (int j = 0; j < i; j++)
    {
      [Ljava.lang.String localString; = arrayOfString;[j];
      entityEscapeMap.put(localString;[2], localString;[0]);
      escapeEntityMap.put(localString;[0], localString;[2]);
      escapeEntityMap.put(localString;[1], localString;[2]);
    }
  }
  
  static java.lang.String escape(java.lang.String paramString)
  {
    StringBuilder localStringBuilder = new StringBuilder(paramString);
    escape(localStringBuilder);
    return localStringBuilder.toString();
  }
  
  static void escape(StringBuilder paramStringBuilder)
  {
    int i = 0;
    while (i < paramStringBuilder.length())
    {
      java.lang.String str = (java.lang.String)entityEscapeMap.get(paramStringBuilder.substring(i, i + 1));
      if (str != null)
      {
        paramStringBuilder.replace(i, i + 1, str);
        i += str.length();
      }
      else
      {
        i++;
      }
    }
  }
  
  static java.lang.String unescape(java.lang.String paramString)
  {
    java.lang.String str = null;
    if (paramString != null)
    {
      StringBuilder localStringBuilder = new StringBuilder(paramString);
      unescape(localStringBuilder);
      str = localStringBuilder.toString();
    }
    return str;
  }
  
  static void unescape(StringBuilder paramStringBuilder)
  {
    int j;
    for (int i = 0;; i = j + 1)
    {
      if (i < paramStringBuilder.length())
      {
        j = paramStringBuilder.indexOf("&", i);
        if (-1 != j) {
          break label26;
        }
      }
      label26:
      int k;
      do
      {
        return;
        k = paramStringBuilder.indexOf(";", j);
      } while (-1 == k);
      java.lang.String str1 = paramStringBuilder.substring(j, k + 1);
      java.lang.String str2 = (java.lang.String)escapeEntityMap.get(str1);
      if (str2 != null) {
        paramStringBuilder.replace(j, k + 1, str2);
      }
    }
  }
  
  static java.lang.String unescapeAndSlideEntityIncdices(java.lang.String paramString, UserMentionEntity[] paramArrayOfUserMentionEntity, URLEntity[] paramArrayOfURLEntity, HashtagEntity[] paramArrayOfHashtagEntity, MediaEntity[] paramArrayOfMediaEntity)
  {
    int i;
    int k;
    label20:
    int n;
    label34:
    int i2;
    label49:
    EntityIndex[] arrayOfEntityIndex;
    int i4;
    int i5;
    int i6;
    StringBuilder localStringBuilder;
    int i7;
    label174:
    char c;
    if (paramArrayOfUserMentionEntity == null)
    {
      i = 0;
      int j = 0 + i;
      if (paramArrayOfURLEntity != null) {
        break label333;
      }
      k = 0;
      int m = j + k;
      if (paramArrayOfHashtagEntity != null) {
        break label340;
      }
      n = 0;
      int i1 = m + n;
      if (paramArrayOfMediaEntity != null) {
        break label347;
      }
      i2 = 0;
      arrayOfEntityIndex = new EntityIndex[i1 + i2];
      int i3 = 0;
      if (paramArrayOfUserMentionEntity != null)
      {
        System.arraycopy(paramArrayOfUserMentionEntity, 0, arrayOfEntityIndex, 0, paramArrayOfUserMentionEntity.length);
        i3 = 0 + paramArrayOfUserMentionEntity.length;
      }
      if (paramArrayOfURLEntity != null)
      {
        System.arraycopy(paramArrayOfURLEntity, 0, arrayOfEntityIndex, i3, paramArrayOfURLEntity.length);
        i3 += paramArrayOfURLEntity.length;
      }
      if (paramArrayOfHashtagEntity != null)
      {
        System.arraycopy(paramArrayOfHashtagEntity, 0, arrayOfEntityIndex, i3, paramArrayOfHashtagEntity.length);
        i3 += paramArrayOfHashtagEntity.length;
      }
      if (paramArrayOfMediaEntity != null) {
        System.arraycopy(paramArrayOfMediaEntity, 0, arrayOfEntityIndex, i3, paramArrayOfMediaEntity.length);
      }
      Arrays.sort(arrayOfEntityIndex);
      i4 = 1;
      i5 = 0;
      i6 = 0;
      localStringBuilder = new StringBuilder(paramString.length());
      i7 = 0;
      if (i7 >= paramString.length()) {
        break label429;
      }
      c = paramString.charAt(i7);
      if (c != '&') {
        break label377;
      }
      int i8 = paramString.indexOf(";", i7);
      if (-1 == i8) {
        break label366;
      }
      java.lang.String str1 = paramString.substring(i7, i8 + 1);
      java.lang.String str2 = (java.lang.String)escapeEntityMap.get(str1);
      if (str2 == null) {
        break label355;
      }
      localStringBuilder.append(str2);
      i7 = i8;
      i6 = 1 - str1.length();
      label269:
      if (i5 < arrayOfEntityIndex.length)
      {
        if (i4 == 0) {
          break label388;
        }
        if (arrayOfEntityIndex[i5].getStart() == i6 + i7)
        {
          arrayOfEntityIndex[i5].setStart(-1 + localStringBuilder.length());
          i4 = 0;
        }
      }
    }
    for (;;)
    {
      i6 = 0;
      i7++;
      break label174;
      i = paramArrayOfUserMentionEntity.length;
      break;
      label333:
      k = paramArrayOfURLEntity.length;
      break label20;
      label340:
      n = paramArrayOfHashtagEntity.length;
      break label34;
      label347:
      i2 = paramArrayOfMediaEntity.length;
      break label49;
      label355:
      localStringBuilder.append(c);
      break label269;
      label366:
      localStringBuilder.append(c);
      break label269;
      label377:
      localStringBuilder.append(c);
      break label269;
      label388:
      if (arrayOfEntityIndex[i5].getEnd() == i6 + i7)
      {
        arrayOfEntityIndex[i5].setEnd(-1 + localStringBuilder.length());
        i5++;
        i4 = 1;
      }
    }
    label429:
    if ((i5 < arrayOfEntityIndex.length) && (arrayOfEntityIndex[i5].getEnd() == paramString.length())) {
      arrayOfEntityIndex[i5].setEnd(localStringBuilder.length());
    }
    return localStringBuilder.toString();
  }
}


/* Location:           F:\neembuu\Research\android_apps\output_jar.jar
 * Qualified Name:     twitter4j.internal.json.HTMLEntity
 * JD-Core Version:    0.7.0.1
 */