/*
 *  Copyright (C) 2010 Shashank Tulsyan
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * NimbusGradColorTest.java
 *
 * Created on Dec 16, 2010, 9:55:31 PM
 */

package neembuu.swing.test;

import java.awt.Color;
import javax.swing.JColorChooser;
import neembuu.rangearray.Range;
import neembuu.rangearray.RangeArray;
import neembuu.rangearray.RangeArrayFactory;
import neembuu.rangearray.RangeArrayParams;
import neembuu.swing.RangeArrayComponent;
import neembuu.swing.RangeArrayElementColorProvider;

/**
 *
 * @author Shashank Tulsyan
 */
public class NimbusGradColorTest extends javax.swing.JFrame {

    private final RangeArray rangeArray;
    private Color color1 = new Color(138,170,231), color2 = Color.ORANGE; 
    /** Creates new form NimbusGradColorTest */
    public NimbusGradColorTest() {
        rangeArray
                 = RangeArrayFactory.newDefaultRangeArray(new RangeArrayParams.Builder().setFileSize(1024).build());
        rangeArray.addElement(0,510,null);
        rangeArray.addElement(512,1023,null);
        initComponents();
        ((RangeArrayComponent)nimbusProgress).setArrayElementColorProvider(new RangeArrayElementColorProvider() {

            @Override
            public Color getColor(Color defaultColor, Range element, SelectionState selectionState) {
                if(element.ending() < 512){return /*defaultColor;*/ color1;}
                return color2;
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nimbusProgress = new RangeArrayComponent(rangeArray);
        chooseColor2 = new javax.swing.JButton();
        chooseColor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chooseColor2.setText("Choose Color 2");
        chooseColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseColor2ActionPerformed(evt);
            }
        });

        chooseColor1.setText("Choose Color 1");
        chooseColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseColor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nimbusProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chooseColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(chooseColor2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(nimbusProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseColor2)
                    .addComponent(chooseColor1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void chooseColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseColor2ActionPerformed
// TODO add your handling code here:
    color2 = JColorChooser.showDialog(this, "Choose color", color1);
    nimbusProgress.repaint();
    System.out.println("2="+color2);
}//GEN-LAST:event_chooseColor2ActionPerformed

private void chooseColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseColor1ActionPerformed
// TODO add your handling code here:
    color1 = JColorChooser.showDialog(this, "Choose color", color1);
    nimbusProgress.repaint();
    System.out.println("1="+color1);
}//GEN-LAST:event_chooseColor1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NimbusGradColorTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseColor1;
    private javax.swing.JButton chooseColor2;
    private javax.swing.JProgressBar nimbusProgress;
    // End of variables declaration//GEN-END:variables

}
